name: Run Tests

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        options:
          - windows
          - ubuntu
        required: true

jobs:
  test:
    name: Tests - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ${{ github.event.inputs.os == 'windows' && 'windows-latest' || 'ubuntu-24.04' }}

    steps:
    - name: Set Initial Workflow Status
      shell: bash
      run: |
        echo "WORKFLOW_STATUS=success" >> $GITHUB_ENV

    - name: Run Tests
      uses: Silverlan/pragma/github_actions/run_common_tests@main
      timeout-minutes: 60
      with:
        import-tests-token: ${{ secrets.PRAGMA_TESTS_IMPORT_TOKEN }}

    - name: Set Failure Workflow Status
      if: failure()
      shell: bash
      run: |
        echo "WORKFLOW_STATUS=failure" >> $GITHUB_ENV
      
    - uses: LouisBrunner/checks-action@v2.0.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        conclusion: ${{ env.WORKFLOW_STATUS }}
        name: "Tests - ${{ matrix.config.os }}"
        output: |
          {"summary":"Test result is '${{ env.WORKFLOW_STATUS }}'. See \"Run Tests\" action for details."}
